"{\"success\":false,\"header\":null,\"data\":null,\"messageKey\":\"error.400\",\"message\":\"error.400\",\"errors\":[],\"exceptions\":[{\"messageData\":{},\"resource\":\"Throwable\",\"messageKey\":\"Throwable\",\"message\":\"Throwable with cause of type 'com.manh.cp.fw.entity.exception.ManhValidationException' was caught and handled by CustomErrorController (see logs for the trace)\",\"stackTrace\":\"java.lang.Throwable: Throwable with cause of type 'com.manh.cp.fw.entity.exception.ManhValidationException' was caught and handled by CustomErrorController (see logs for the trace)\\n\"}],\"messages\":{\"Message\":[{\"Type\":\"ERROR\",\"Code\":\"CodeTypeId\",\"Description\":\"Invalid data for the field CodeTypeId:CodeTypeId:Secondary_UPC\",\"ShortDescription\":null,\"ErrorCode\":null,\"ErrorField\":null,\"ResourceId\":null,\"QuickInfo\":false,\"BusinessKeys\":{}},{\"Type\":\"ERROR\",\"Code\":\"CodeTypeId\",\"Description\":\"Invalid data for the field CodeTypeId:CodeTypeId:Secondary_UPC\",\"ShortDescription\":null,\"ErrorCode\":null,\"ErrorField\":null,\"ResourceId\":null,\"QuickInfo\":false,\"BusinessKeys\":{}},{\"Type\":\"ERROR\",\"Code\":\"CodeTypeId\",\"Description\":\"Invalid data for the field CodeTypeId:CodeTypeId:Secondary_UPC\",\"ShortDescription\":null,\"ErrorCode\":null,\"ErrorField\":null,\"ResourceId\":null,\"QuickInfo\":false,\"BusinessKeys\":{}}],\"Size\":3},\"rootCause\":\"java.lang.Throwable: Throwable with cause of type 'com.manh.cp.fw.entity.exception.ManhValidationException' was caught and handled by CustomErrorController (see logs for the trace)\",\"cloudComponent\":\"com-manh-cp-item:docker,cloud,kubernetes:8080\",\"cloudComponentHostName\":\"42369f8690d8\",\"requestUri\":\"/error\",\"statusCode\":\"BAD_REQUEST\"}"